name: R-CMD-check
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.3'
      - run: Rscript -e "print('R installed successfully')"

      - name: Install dependencies
        run: Rscript -e "install.packages(c('testthat','dplyr','magrittr','tidyr','readr','stringr','reshape2'))"

      - name: Run Tests
        run: Rscript -e "library(testthat); test_dir('tests')"
